import { IntegrationProvider } from '@prisma/client';
import { createMeliRepository } from '@/lib/mercado-livre/meli-repository';
import type {
  InventoryProvider,
  NormalizedProduct,
  NormalizedAlert,
  NormalizedOverviewMetrics,
} from './types';

/**
 * Mercado Livre implementation of the InventoryProvider interface.
 * Wraps the Mercado Livre repository and adapts its data to normalized DTOs.
 */
export class MeliInventoryProvider implements InventoryProvider {
  readonly provider = IntegrationProvider.MERCADO_LIVRE;

  async getProducts(integrationId: string, take = 50, skip = 0): Promise<NormalizedProduct[]> {
    const repo = createMeliRepository({ integrationId });
    const meliProducts = await repo.getProducts(take, skip);

    return meliProducts.map((product) => ({
      id: product.id,
      externalId: product.meliItemId,
      provider: IntegrationProvider.MERCADO_LIVRE,
      name: product.title,
      sku: product.sku ?? '',
      costPrice: product.costPrice,
      salePrice: product.salePrice,
      currentStock: product.currentStock,
      image: product.thumbnail ?? null,
      categoryName: null, // Category not included in basic product query
      createdAt: product.createdAt,
      updatedAt: product.updatedAt,
    }));
  }

  async getProductById(
    integrationId: string,
    externalId: string
  ): Promise<NormalizedProduct | null> {
    const repo = createMeliRepository({ integrationId });
    const product = await repo.getProductById(externalId);

    if (!product) return null;

    return {
      id: product.id,
      externalId: product.meliItemId,
      provider: IntegrationProvider.MERCADO_LIVRE,
      name: product.title,
      sku: product.sku ?? '',
      costPrice: product.costPrice,
      salePrice: product.salePrice,
      currentStock: product.currentStock,
      image: product.thumbnail ?? null,
      categoryName: null,
      createdAt: product.createdAt,
      updatedAt: product.updatedAt,
    };
  }

  async getAlerts(integrationId: string): Promise<NormalizedAlert[]> {
    // Mercado Livre alerts will be implemented in Phase 4 (Inngest handlers)
    // For now, return empty array - alerts are generated by background jobs
    return [];
  }

  async getOverviewMetrics(
    integrationId: string,
    _params: Record<string, unknown>
  ): Promise<NormalizedOverviewMetrics> {
    // Mercado Livre overview metrics will be implemented in Phase 4
    // For now, return zero values - metrics are calculated by background jobs
    return {
      totalProducts: 0,
      alertCounts: {
        fine: 0,
        rupture: 0,
        deadStock: 0,
        opportunity: 0,
        liquidation: 0,
      },
      riskCounts: {
        low: 0,
        medium: 0,
        high: 0,
        critical: 0,
      },
      totalCapitalStuck: 0,
      totalEstimatedLoss: 0,
    };
  }
}
